default_install_hook_types:
-   pre-commit
-   commit-msg

repos:
-   repo: https://github.com/IldarMinaev/pre-commit-tests
    rev: v1.0.1
    hooks:
    -   id: org-hook
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.3.0
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]
        args: [--strict, --verbose]
-   repo: local
    hooks:
    -   id: echo-sample
        name: echo-sample
        entry: echo
        language: system
        args: [".pre-commit-config.yaml present"]
        always_run: true
